# Default database configuration

development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: sqlite3
  database: db/production.sqlite3
                                    
passenger:
  development
  
# paths specific for the Gromit server
gromit:
  adapter: sqlite3
  # Keep data between capistrano deployments by putting the database in shared/db
  # The db:migrate version is kept in the database itself
  database: /var/capistrano/retail/shared/db/production.sqlite3
  timeout: 5000

# paths specific for the jsHub server
jshub:
  adapter: sqlite3
  # Keep data between capistrano deployments by putting the database in shared/db
  # The db:migrate version is kept in the database itself
  database: /var/capistrano/retail/shared/db/production.sqlite3
  timeout: 5000 